param(
  [string]$Root = (Resolve-Path ".").Path,
  [string]$GodotPath = "D:\Programming\godot_workspace\bin\Godot_v4.3-stable_win64_console.exe",
  [string]$ArchitecturalManifest = "",
  [string[]]$ArchitecturalManifests = @(
    "docs/architectural-gates/warning-refactor-gate.md",
    "docs/architectural-gates/strict-refactor-gate.md",
    "docs/architectural-gates/release-blocking-gate.md"
  ),
  [string]$RequestLedger = "docs/request-ledgers/2026-06-02-refactor-harness-quality-gate.md",
  [string]$ArtifactLedger = "docs/artifact-ledgers/ltl-quality-gate-latest.md",
  [switch]$SkipRequestAnalysisGate,
  [switch]$SkipArchitecturalGate,
  [switch]$SkipGodotContracts
)

$ErrorActionPreference = "Stop"

function Fail($Message) {
  Write-Error "LTL_QUALITY_GATE_FAIL: $Message"
  exit 1
}

function Resolve-FullPath($Path) {
  return [System.IO.Path]::GetFullPath($Path).TrimEnd("\", "/")
}

function Invoke-NativeStep($Name, $Command, [string[]]$Arguments, [string]$ExpectedMarker = "") {
  Write-Host "== $Name ==" -ForegroundColor Cyan
  $previousErrorActionPreference = $ErrorActionPreference
  $ErrorActionPreference = "Continue"
  $output = & $Command @Arguments 2>&1
  $exitCode = $LASTEXITCODE
  $ErrorActionPreference = $previousErrorActionPreference
  $output | ForEach-Object { Write-Host $_ }

  $joinedOutput = $output | Out-String
  if ($joinedOutput -match "SCRIPT ERROR|Parse Error|Failed to load script|missing Godot formal script") {
    $exitCode = 1
  }
  if (-not [string]::IsNullOrWhiteSpace($ExpectedMarker) -and -not ($joinedOutput -match [regex]::Escape($ExpectedMarker))) {
    $exitCode = 1
  }
  if ($exitCode -ne 0) {
    Fail "$Name failed with exit code $exitCode"
  }
}

function Invoke-GodotScript($Name, $Script, $ExpectedMarker) {
  $logName = ($Name.ToLowerInvariant() -replace "[^a-z0-9_.-]+", "-").Trim("-") + ".log"
  $logPath = "app-LTL/.tmp-godot-logs/$logName"
  Invoke-NativeStep $Name $GodotPath @(
    "--headless",
    "--path", "app-LTL",
    "--log-file", "res://.tmp-godot-logs/$logName",
    "--script", $Script,
    "--quit"
  ) $ExpectedMarker
  Add-ArtifactEntry $Name $logPath $ExpectedMarker
}

function Initialize-ArtifactLedger($Path) {
  $dir = Split-Path -Parent $Path
  if (-not [string]::IsNullOrWhiteSpace($dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
  }
  Set-Content -LiteralPath $Path -Encoding UTF8 -Value @(
    "# LTL Quality Gate Artifact Ledger",
    "",
    'Generated by `tools/run-ltl-quality-gate.ps1`.',
    "",
    "## Artifacts",
    ""
  )
}

function Add-ArtifactEntry($Name, $Path, $Marker) {
  if ([string]::IsNullOrWhiteSpace($script:ArtifactLedgerFullPath)) {
    return
  }
  Add-Content -LiteralPath $script:ArtifactLedgerFullPath -Encoding UTF8 -Value @(
    "- $Name",
    "  - Path: ``$Path``",
    "  - Expected marker: ``$Marker``"
  )
}

$resolvedRoot = Resolve-FullPath $Root
if (-not (Test-Path -LiteralPath $resolvedRoot)) {
  Fail "Root not found: $Root"
}
if (-not (Test-Path -LiteralPath $GodotPath)) {
  Fail "Godot executable not found: $GodotPath"
}

$godotUserRoot = Join-Path $resolvedRoot ".godot-user"
$godotRoaming = Join-Path $godotUserRoot "Roaming"
$godotLocal = Join-Path $godotUserRoot "Local"
$godotLogDir = Join-Path $resolvedRoot "app-LTL\.tmp-godot-logs"
New-Item -ItemType Directory -Force -Path $godotRoaming, $godotLocal, $godotLogDir | Out-Null
$env:APPDATA = $godotRoaming
$env:LOCALAPPDATA = $godotLocal
$script:ArtifactLedgerFullPath = if ([string]::IsNullOrWhiteSpace($ArtifactLedger)) { "" } else { [System.IO.Path]::GetFullPath((Join-Path $resolvedRoot $ArtifactLedger)) }
if (-not [string]::IsNullOrWhiteSpace($script:ArtifactLedgerFullPath)) {
  Initialize-ArtifactLedger $script:ArtifactLedgerFullPath
}

$activeArchitecturalManifests = @()
if (-not [string]::IsNullOrWhiteSpace($ArchitecturalManifest)) {
  $activeArchitecturalManifests += $ArchitecturalManifest
}
$activeArchitecturalManifests += $ArchitecturalManifests
$activeArchitecturalManifests = $activeArchitecturalManifests |
  Where-Object { -not [string]::IsNullOrWhiteSpace($_) } |
  Select-Object -Unique

Push-Location $resolvedRoot
try {
  if (-not $SkipRequestAnalysisGate) {
    Invoke-NativeStep "request analysis gate" "powershell" @(
      "-NoProfile", "-ExecutionPolicy", "Bypass",
      "-File", "LTL-harness/tools/request-analysis-gate.ps1",
      "-Ledger", $RequestLedger,
      "-Mode", "pre-complete",
      "-RequireArtifactLedger"
    ) "REQUEST_ANALYSIS_GATE_OK"

    Invoke-NativeStep "request analysis gate self-test" "powershell" @(
      "-NoProfile", "-ExecutionPolicy", "Bypass",
      "-File", "LTL-harness/tools/request-analysis-gate.tests.ps1"
    ) "REQUEST_ANALYSIS_GATE_TESTS_OK"

    Invoke-NativeStep "request source map self-test" "powershell" @(
      "-NoProfile", "-ExecutionPolicy", "Bypass",
      "-File", "LTL-harness/tools/request-source-map.tests.ps1"
    ) "REQUEST_SOURCE_MAP_TESTS_OK"
  }

  Invoke-NativeStep "source map gate" "powershell" @(
    "-NoProfile", "-ExecutionPolicy", "Bypass",
    "-File", "LTL-harness/tools/source-map-gate.ps1",
    "-Root", $resolvedRoot
  ) "SOURCE_MAP_GATE_OK"

  Invoke-NativeStep "source map gate self-test" "powershell" @(
    "-NoProfile", "-ExecutionPolicy", "Bypass",
    "-File", "LTL-harness/tools/source-map-gate.tests.ps1"
  ) "SOURCE_MAP_GATE_TESTS_OK"

  Invoke-NativeStep "test size gate" "powershell" @(
    "-NoProfile", "-ExecutionPolicy", "Bypass",
    "-File", "LTL-harness/tools/test-size-gate.ps1",
    "-Root", $resolvedRoot
  ) "TEST_SIZE_GATE_OK"

  Invoke-NativeStep "test size gate self-test" "powershell" @(
    "-NoProfile", "-ExecutionPolicy", "Bypass",
    "-File", "LTL-harness/tools/test-size-gate.tests.ps1"
  ) "TEST_SIZE_GATE_TESTS_OK"

  Invoke-NativeStep "runtime size gate" "powershell" @(
    "-NoProfile", "-ExecutionPolicy", "Bypass",
    "-File", "LTL-harness/tools/runtime-size-gate.ps1",
    "-Root", $resolvedRoot
  ) "RUNTIME_SIZE_GATE_OK"

  Invoke-NativeStep "runtime size gate self-test" "powershell" @(
    "-NoProfile", "-ExecutionPolicy", "Bypass",
    "-File", "LTL-harness/tools/runtime-size-gate.tests.ps1"
  ) "RUNTIME_SIZE_GATE_TESTS_OK"

  Invoke-NativeStep "formal stack gate" "powershell" @(
    "-NoProfile", "-ExecutionPolicy", "Bypass",
    "-File", "LTL-harness/tools/ltl-tech-stack-gate.ps1",
    "-Root", $resolvedRoot
  ) "LTL_TECH_STACK_GATE_OK"

  Invoke-NativeStep "i18n text gate" "powershell" @(
    "-NoProfile", "-ExecutionPolicy", "Bypass",
    "-File", "LTL-harness/tools/i18n-text-gate.ps1",
    "-Root", $resolvedRoot
  ) "I18N_TEXT_GATE_OK"

  Invoke-NativeStep "i18n text gate self-test" "powershell" @(
    "-NoProfile", "-ExecutionPolicy", "Bypass",
    "-File", "LTL-harness/tools/i18n-text-gate.tests.ps1"
  ) "I18N_TEXT_GATE_TESTS_OK"

  if (-not $SkipArchitecturalGate) {
    foreach ($manifest in $activeArchitecturalManifests) {
      $manifestName = [System.IO.Path]::GetFileNameWithoutExtension($manifest)
      Invoke-NativeStep "architectural gate ($manifestName)" "powershell" @(
        "-NoProfile", "-ExecutionPolicy", "Bypass",
        "-File", "LTL-harness/tools/architectural-gate.ps1",
        "-Root", $resolvedRoot,
        "-ManifestPath", $manifest
      ) "ARCHITECTURAL_GATE_OK"
    }
  }

  Invoke-NativeStep "page contract gate" "powershell" @(
    "-NoProfile", "-ExecutionPolicy", "Bypass",
    "-File", "LTL-harness/tools/page-contract-gate.ps1",
    "-Root", $resolvedRoot,
    "-GodotPath", $GodotPath
  ) "PAGE_CONTRACT_GATE_OK"

  Invoke-NativeStep "transition safety gate" "powershell" @(
    "-NoProfile", "-ExecutionPolicy", "Bypass",
    "-File", "LTL-harness/tools/transition-safety-gate.ps1",
    "-Root", $resolvedRoot,
    "-GodotPath", $GodotPath,
    "-Ledger", $RequestLedger
  ) "TRANSITION_SAFETY_GATE_OK"

  Invoke-NativeStep "transition safety gate self-test" "powershell" @(
    "-NoProfile", "-ExecutionPolicy", "Bypass",
    "-File", "LTL-harness/tools/transition-safety-gate.tests.ps1"
  ) "TRANSITION_SAFETY_GATE_TESTS_OK"

  if (-not $SkipGodotContracts) {
    Invoke-GodotScript "reward ceremony contracts" "tests/run_reward_ceremony_contract.gd" "REWARD_CEREMONY_CONTRACT_OK"
    Invoke-GodotScript "full Godot contracts" "tests/godot_contract_runner.gd" "GODOT_CONTRACTS_OK"
  }
}
finally {
  Pop-Location
}

Write-Output "LTL_QUALITY_GATE_OK"
